import { ArrowDownRight, ArrowUpRight, Code2, Network, Mail } from 'lucide-react'
import { Header } from './components/Header'
import { SectionHeading } from './components/SectionHeading'
import { VehicleVisual } from './components/VehicleVisual'
import { FaqItem } from './components/FaqItem'
import { capabilities, domains, faq, journey, research } from './data/portfolio'

function App() {
  return <><div id="top" /><Header /><main>
    <section className="hero shell"><div className="hero-meta eyebrow">Computer Science / AI / Automotive Systems</div><div className="hero-content"><h1>Building intelligent systems<br />for the <em>physical world.</em></h1><div className="hero-bottom"><p>I build systems that connect artificial intelligence, real-time data, and physical machines - from vehicle telemetry platforms and digital twins to computer vision systems.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore my work <ArrowDownRight size={17}/></a><a className="text-link" href="#contact">Let's connect <ArrowDownRight size={16}/></a></div></div></div><div className="hero-orbit" aria-hidden="true"><span>PHYSICAL SYSTEMS</span><i /></div></section>
    <section className="credibility shell"><div className="domain-list">{domains.map(d => <div className="domain" key={d.number}><span>{d.number}</span><div><p>{d.label}</p><strong>{d.value}</strong></div></div>)}</div></section>
    <section id="work" className="work shell"><SectionHeading label="01 / Selected work" title="Systems built with a view beyond the screen." copy="Systems built to explore how software can understand, model, and interact with the physical world." />
      <article className="project feature reveal"><div className="project-copy"><p className="eyebrow">Flagship project / In development</p><h3>DriveVitals</h3><h4>Vehicle Intelligence & Digital Twin Platform</h4><p>DriveVitals transforms raw vehicle data into an evolving digital representation of vehicle health, driver behavior, and fleet performance.</p><ul>{['Python', 'FastAPI', 'React', 'WebSockets', 'PostgreSQL', 'Machine Learning', 'Digital Twins', 'Vehicle Telemetry'].map(x => <li key={x}>{x}</li>)}</ul><a className="text-link" href="#contact">Explore the system <ArrowUpRight size={16}/></a></div><VehicleVisual /></article>
      <div className="project-grid"><article className="project compact reveal"><div><p className="eyebrow">Computer vision access control</p><h3>Smart Door<br />Security System</h3><p>A system designed to identify and verify individuals in real time while connecting perception with physical access control.</p></div><div className="project-footer"><span>Computer Vision / Python / Embedded Systems</span><ArrowUpRight size={18}/></div></article><article className="project future reveal"><p className="eyebrow">Exploring next</p><h3>What physical systems need <em>to say.</em></h3><p>Researching how intelligent systems can perceive, model, and respond to the physical world.</p><div className="orbital-mark">+</div></article></div>
    </section>
    <section id="tools" className="tools shell"><SectionHeading label="02 / Capabilities" title="Tools for building intelligent systems" /><div className="capability-grid">{capabilities.map((cap, index) => <article className="capability reveal" key={cap.title}><span>0{index + 1}</span><h3>{cap.title}</h3><div>{cap.items.map(item => <p key={item}>{item}</p>)}</div></article>)}</div></section>
    <section id="experience" className="experience shell"><SectionHeading label="03 / Journey" title="Learning to build for a world in motion." /><div className="timeline">{journey.map((item, i) => <article className="timeline-item reveal" key={item.date}><span>{item.date}</span><div><i>0{i + 1}</i><h3>{item.title}</h3><p>{item.copy}</p></div></article>)}</div></section>
    <section id="research" className="research shell"><SectionHeading label="04 / Research & thinking" title="Questions that lead the work." /><div className="research-list">{research.map(item => <article className="research-item reveal" key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.copy}</p><ArrowUpRight size={19}/></article>)}</div></section>
    <section className="faq shell"><SectionHeading label="05 / FAQ" title="A few useful answers." /><div className="faq-list">{faq.map(([q,a]) => <FaqItem key={q} question={q} answer={a} />)}</div></section>
    <section id="contact" className="contact"><div className="shell contact-inner"><p className="eyebrow">06 / Start a conversation</p><h2>Let's build something <em>intelligent.</em></h2><div className="contact-footer"><p>Interested in AI, automotive intelligence, real-time systems, or the future of intelligent machines? I'm always open to meaningful conversations.</p><a className="button button-light" href="mailto:your-email@example.com">Get in touch <ArrowUpRight size={18}/></a></div><div className="socials"><a href="mailto:your-email@example.com"><Mail size={17}/> Email</a><a href="#"><Code2 size={17}/> GitHub</a><a href="#"><Network size={17}/> LinkedIn</a></div></div></section>
  </main><footer className="shell"><span>Haris Kamal Rana</span><span>AI / Automotive Intelligence / Digital Twins</span><span>(c) {new Date().getFullYear()} / Haris Kamal Rana</span></footer></>
}
export default App
