import { ArrowDownRight, ArrowUpRight, Code2, Download, Mail, Network, Phone } from 'lucide-react'
import { FaqItem } from './components/FaqItem'
import { HeaderRefined } from './components/HeaderRefined'
import { RevealObserver } from './components/RevealObserver'
import { SectionHeading } from './components/SectionHeading'
import { TechnicalVisual } from './components/TechnicalVisual'
import { DriveVitalsVisual } from './components/DriveVitalsVisual'
import { HeroSystemVisual } from './components/HeroSystemVisual'
import { capabilities, domains, faq, journey, research } from './data/refinedPortfolio'

function AppRefined() {
  return <><RevealObserver /><div id="top" /><HeaderRefined /><main>
    <section className="hero shell"><div className="hero-meta eyebrow" data-reveal>Computer Science / AI / Automotive Systems</div><div className="hero-content" data-reveal><h1>Building intelligent systems<br />for the <em>physical world.</em></h1><div className="hero-bottom"><p>I build intelligent systems that connect artificial intelligence, real-time data, and physical machines - from vehicle telemetry platforms and digital twins to computer vision systems.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore my work <ArrowDownRight size={17}/></a><a className="text-link" href="/Haris-Kamal-Rana-CV.pdf" download>View resume <Download size={15}/></a></div></div></div><HeroSystemVisual /></section>
    <section className="credibility shell"><div className="domain-list domain-list-four">{domains.map(d => <div className="domain" data-reveal key={d.number}><span>{d.number}</span><div><p>{d.label}</p><strong>{d.value}</strong></div></div>)}</div></section>
    <section id="work" className="work shell"><SectionHeading label="01 / Selected work" title="Systems built with a view beyond the screen." copy="Self-initiated engineering projects exploring how software can understand, model, and interact with physical systems." />
      <article className="project feature" data-reveal><div className="project-copy"><p className="eyebrow">Project Lead & Software Engineer / July 2026 - Present</p><h3>DriveVitals</h3><h4>Vehicle Intelligence & Digital Twin Platform</h4><p>DriveVitals is an AI-powered Fleet Intelligence and Digital Twin platform for simulating commercial fleet operations, vehicle telemetry, driver behaviour, and predictive fleet analytics.</p><p className="project-detail">Architected the backend, digital twin execution pipeline, simulation runtime, fleet management systems, telemetry generation, analytics integration, Version 1 APIs, and PostgreSQL data model. Future architecture includes OBD-II integration and machine learning models.</p><ul>{['Python', 'FastAPI', 'REST APIs', 'WebSockets', 'PostgreSQL', 'SQLAlchemy', 'Pydantic', 'Digital Twins', 'Fleet Analytics', 'Physics Simulation', 'Machine Learning'].map(x => <li key={x}>{x}</li>)}</ul><a className="text-link" href="#contact">Discuss the system <ArrowUpRight size={16}/></a></div><DriveVitalsVisual /></article>
      <div className="project-grid project-grid-three"><article className="project compact smart-door" data-reveal><div><p className="eyebrow">Computer vision access control</p><h3>Smart Door<br />Security System</h3><p>A real-time facial recognition security system built with Python and OpenCV for automated identity verification and physical access control.</p><div className="project-mini"><TechnicalVisual kind="vision" label="Facial recognition interface" /></div></div><div className="project-footer"><span>Python / OpenCV / Computer Vision</span><ArrowUpRight size={18}/></div></article><article className="project compact workshop" data-reveal><div><p className="eyebrow">Relational database system</p><h3>Vehicle Service Workshop Database</h3><p>Managing service operations, customer records, repair history, maintenance workflows, scheduling, reporting, and optimized queries.</p></div><div className="project-footer"><span>SQL / MySQL / Database Design</span><ArrowUpRight size={18}/></div></article><article className="project future" data-reveal><p className="eyebrow">Engineering practice</p><h3>Built with systems thinking.</h3><p>Leading the DriveVitals team with milestone planning, pull requests, reviews, feature branches, and controlled merges.</p><div className="orbital-mark">+</div></article></div>
    </section>
    <section id="tools" className="tools shell"><SectionHeading label="02 / Capabilities" title="Tools for building intelligent systems" /><div className="capability-grid capability-grid-refined">{capabilities.map((cap, index) => <article className="capability" data-reveal key={cap.title}><span>0{index + 1}</span><TechnicalVisual kind={cap.visual} label={cap.title} /><h3>{cap.title}</h3><div>{cap.items.map(item => <p key={item}>{item}</p>)}</div></article>)}</div></section>
    <section id="experience" className="experience shell"><SectionHeading label="03 / Journey" title="Learning to build for a world in motion." /><div className="timeline">{journey.map((item, i) => <article className="timeline-item" data-reveal key={item.date}><span>{item.date}</span><div><i>0{i + 1}</i><h3>{item.title}</h3><h4>{item.organization}</h4><p>{item.copy}</p></div></article>)}</div></section>
    <section id="research" className="research shell"><SectionHeading label="04 / Research & thinking" title="Questions that lead the work." /><div className="research-list">{research.map(item => <article className="research-item" data-reveal key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.copy}</p><ArrowUpRight size={19}/></article>)}</div></section>
    <section className="faq shell"><SectionHeading label="05 / FAQ" title="A few useful answers." /><div className="faq-list">{faq.map(([q,a]) => <FaqItem key={q} question={q} answer={a} />)}</div></section>
    <section id="contact" className="contact"><div className="shell contact-inner"><p className="eyebrow">06 / Start a conversation</p><h2>Let's build something <em>intelligent.</em></h2><div className="contact-footer"><p>Interested in artificial intelligence, automotive intelligence, real-time systems, or the future of intelligent machines? I'm always open to meaningful conversations.</p><a className="button button-light" href="mailto:harriskamal23@gmail.com">Get in touch <ArrowUpRight size={18}/></a></div><div className="socials"><a href="mailto:harriskamal23@gmail.com"><Mail size={17}/> harriskamal23@gmail.com</a><a href="tel:+923098999565"><Phone size={17}/> +92 309 8999565</a><a href="https://github.com/harisrana-dev" target="_blank" rel="noreferrer"><Code2 size={17}/> GitHub</a><a href="https://www.linkedin.com/in/hariskamalrana" target="_blank" rel="noreferrer"><Network size={17}/> LinkedIn</a><a href="/Haris-Kamal-Rana-CV.pdf" download><Download size={17}/> Download CV</a></div></div></section>
  </main><footer className="shell"><span>Haris Kamal Rana</span><span>AI / Automotive Intelligence / Digital Twins</span><span>(c) {new Date().getFullYear()} / Haris Kamal Rana</span></footer></>
}
export default AppRefined
